### ISSUE TITLE
Issue when sending big file

### ISSUE THREAD

**Issue by peteruithoven** [Doodle3D/doodle3d-firmware#13]
When sending a big file I got the following error:
```
XMLHttpRequest cannot load http://192.168.5.1/d3dapi/printer/print. Origin http://doodle3d-client.local is not allowed by Access-Control-Allow-Origin.
```
It's at sendIndex: 114000 of 144726 (sendLength: 1500)

Other requests like info/status still work on the same page. 

When I send the same data (gcode, start and first) trough a rest extension directly to the api it works without issues and very fast. 

The send print part timeout is 5 seconds, so that shouldn't be a problem. 

While writing this it suddenly continues accepting the print parts and completed sending all the parts.

**Comment by woutgg** [comment]
Even though having sent quite large files, we have not encountered this recently.
