### ISSUE TITLE
Full factory reset/wipe?

### ISSUE THREAD

**Issue by daid** [Doodle3D/doodle3d-firmware#23]
Is it possible to do a full factory reset/wipe everything? I think my box is corrupted because I'm seeing some odd behavior even on SSH. So I would like to do a full clean install.

**Comment by Sup33r** [comment]
Hey, @peteruithoven ! Do you still know (after these 6 or so years) how to reflash the doodle3d wifibox? I would read the website if i could, but that is unfortunatly down 😞.

Thanks!
//Viktor

**Comment by peteruithoven** [comment]
I don't know the state of your wifi box, or your technical prowess. 

You could try running the (safe)update web interface that used to be on the website:
https://github.com/Doodle3D/update

The interesting bit of logic:
https://github.com/Doodle3D/update/blob/master/js/main.js#L252-L316

It looks like it uses the update API that's on the wifi box:
https://github.com/Doodle3D/doodle3d-firmware/blob/master/src/rest/api/api_update.lua


If you have the .bin you could use `scp` to copy it to the device:
```
scp bin/ar71xx/openwrt-ar71xx-generic-tl-mr3020-v1-squashfs-factory.bin root@192.168.1.1:/tmp/
```

And then ssh into the device and use the `sysupgrade` to flash it:
```
sysupgrade -n /tmp/openwrt-ar71xx-generic-tl-mr3020-v1-squashfs-factory.bin
```

It's indeed been a while, I hope this helps.

**Comment by Sup33r** [comment]
Thanks for the reply!

How would I go about ssh:ing into the device? Do you know the username and password?

**Comment by peteruithoven** [comment]
I can probably figure that out, but I would recommend trying the API approach first?

**Comment by Sup33r** [comment]
That would probably be easier if i wanted to keep the doodle3d firmware, but i want to change to a different firmware, which i think you only can do if you connect to the device via ssh. No worries if you cant get the username and password 😄

**Comment by peteruithoven** [comment]
Ah sure, but we agreed on not publicizing the login details openly, let me know how I can reach out to you privately.
