### ISSUE TITLE
config WIFIBOX_WIRELESS_DEVICE not used

### ISSUE THREAD

**Issue by morriswinkler** [Doodle3D/doodle3d-firmware#25]
As far as i figured config WIFIBOX_WIRELESS_DEVICE in Config.in is not used, 

i guess it should be used to set 

M.DFL_DEVICE_FALLBACK = 'radio0'

in src/network/wlanconfig.lua

please correct me

**Comment by peteruithoven** [comment]
If the config isn't removed, I don't understand why this is closed?

**Comment by companje** [comment]
feel free to reopen the issue if you think we should invest time in this.

**Comment by peteruithoven** [comment]
Not really, but I've added a tag to clarify that we won't fix this.
