### ISSUE TITLE
Fix version in banner

### ISSUE THREAD

**Issue by peteruithoven** [Doodle3D/doodle3d-firmware#36]
Currently when you ssh into the WiFi-Box, you get the following "banner":
```
BusyBox v1.22.1 (2015-06-10 15:45:30 UTC) built-in shell (ash)
Enter 'help' for a list of built-in commands.

........D o o d l e 3 D
.......________     _____  _____  v \$(PACKAGE_VERSION)
....../  /  /  |__ /  __/ /  - /___ __
...../  /  /  /--//  _|-//  --| . /v /
..../________/__//__/__//____/___/_^_\
...
..A cad in a box.
.
```
This is set by our postinstall script: 
https://github.com/Doodle3D/doodle3d-firmware/blob/master/post-install.sh#L36

We should really fix the `$(PACKAGE_VERSION)`

**Comment by companje** [comment]
the $(PACKAGE_VERSION) was removed at some point. I'm closing this issue.
