### ISSUE TITLE
Ajax communication message formatting

### ISSUE THREAD

**Issue by woutgg** [Doodle3D/doodle3d-firmware#4]
The current comma-separated values are rather restrictive. Json is more versatile (e.g. key/value pairs) and handles quotation and related issues out of the box.

At the very least, the current format should be extended with key/value fields.

**Comment by peteruithoven** [comment]
@woutgg Do you remember which messages you where referring to here? The API is all in json.

**Comment by woutgg** [comment]
I think it was about the initial message formatting. csv was refactored to json in [this commit](https://github.com/Doodle3D/doodle3d-firmware/commit/115e6a7eff7c8b916c2eb3e9a05a2def836cb001#diff-399535253a1e10a62c271df810eaf060L2), introducing use of [serializeAsJson()](https://github.com/Doodle3D/doodle3d-firmware/blob/115e6a7eff7c8b916c2eb3e9a05a2def836cb001/src/rest/response.lua#L54). Closing this one.

**Comment by peteruithoven** [comment]
Thanks for the clarification
