### ISSUE TITLE
WiFi-Box can't connect to network with login / sign-in

### ISSUE THREAD

**Issue by peteruithoven** [Doodle3D/doodle3d-firmware#43]
When you connect to a wireless WiFi hotspot with a sign-in you have to go to your browser and must accept terms and conditions to gain access to the Internet.

But a WiFi-Box doesn't do this, and therefore can't fully connect to the network, and it can't reach the internet. Currently this makes the box inaccessible without a ethernet cable.
We'll need to research whether we can make the WiFi-box "sign-in" in these kind of networks.

Original issue: https://github.com/Doodle3D/doodle3d-client/issues/279

**Comment by olijf** [comment]
Is this still something to look at? Seems to me this is a wont fix (as eg the chromecast is also unable to connect to such a network.) 
If the 'accept' splashpage is known we could do a simple wget from the wifibox... otherwise we would need to forward the accept page to present to the user.

**Comment by companje** [comment]
I agree we should not create a solution that will be able to login on such networks.
However the WiFi-Box will get into an unreachable state when this happens because it has successfully connected to a network although there's no way for it to reach the internet. We should implement that when it is not able to sign-in at connect.doodle3d.com it should fallback to accesspoint mode.

**Comment by peteruithoven** [comment]
Are we sure ChromeCast can't handle this? I have a ChromeCast but besides the train WiFi I don't know of a network to test this). 

I agree with Rick let's close this issue and fix issues like:
https://github.com/Doodle3D/doodle3d-firmware/issues/41
https://github.com/Doodle3D/doodle3d-client/issues/209

**Comment by peteruithoven** [comment]
ChromeCast doesn't seem to handle it: http://www.howtogeek.com/195762/ask-htg-how-can-i-use-my-google-chromecast-in-a-hotel-room/
