### ISSUE TITLE
Set total lines manually

### ISSUE THREAD

**Issue by peteruithoven** [Doodle3D/doodle3d-firmware#51]
Currently the `total_lines` is probably `buffered_lines` + `current_line`, but this means that while still sending (buffering) gcode total_lines is far of the actual total lines. 
It would be interesting to allow overriding this in the `/printer/print` api request. 

Also see: https://github.com/Doodle3D/print3d/issues/31

**Comment by woutgg** [comment]
Implemented [here in the server](https://github.com/Doodle3D/print3d/commit/c9a07a1e23ea955a42a1a6408612596c8a3afd56), [here in the firmware](https://github.com/Doodle3D/doodle3d-firmware/commit/de16721b854a193e4652c433354745b69f78d8e7) and [here in the client](https://github.com/Doodle3D/doodle3d-client/commit/4f5e1143b4d392dc47c48daca7e03a9516807fe2).
