### ISSUE TITLE
Calling function 'list' in API module 'sketch' somehow failed

### ISSUE THREAD

**Issue by peteruithoven** [Doodle3D/doodle3d-firmware#56]
02-24 14:50:02 [ENTR] (error)  : calling function 'list' in API module 'sketch' somehow failed ('/usr/share/lua/wifibox/rest/api/api_sketch.lua:54: cannot open /root/sketches: No such file or directory')

It could be that on "fresh" WiFi-Boxes this folder doesn't exist yet.

**Comment by peteruithoven** [comment]
Nice :+1:

**Comment by companje** [comment]
thanks wouter
