### ISSUE TITLE
no dhcp address in station mode

### ISSUE THREAD

**Issue by woutgg** [Doodle3D/doodle3d-firmware#6]
After associating with an access point, the wlan interface (wlan-br to be precise) does not get an IP address.
According to the log it is offered an address but it never gets assigned.

Hint 1: When doing a regular setup (i.e. vanilla build, using luci), everything works fine. Where are the differences?

Hint 2: dnsmasq logs that it received a DHCP packet but that the interface has no address. See [this link](https://forum.openwrt.org/viewtopic.php?id=27241). Adding the 'notinterface' setting merely prevents the log message.

Hint 3: setting a dummy address in the network configuration on the wlan interface (e.g. 192.168.11.1/24) seems to trigger udhcpc to be started and receive an address but it still does not get assigned.

**Comment by olijf** [comment]
Is this still an issue? Seems interface wlan-br does not exists in current builds?
Seeing this is a bridge interface (suffix br) I am wondering why it would need an IP in the first place.

**Comment by peteruithoven** [comment]
Please try it out, see if you can reproduce it. Do you have enough information to do this?

**Comment by olijf** [comment]
Not nearly, but this morning I tried to reproduse this but as I said... I can't find the wlan0-br interface in the recent builds.

**Comment by peteruithoven** [comment]
You're sure this issue isn't mentioned in `logead` or the `wifibox.log`? If not I would close the issue.

**Comment by companje** [comment]
I'm closing this issue now. Feel free to re-open if needed.
